title: InCube Core Library
email: info@incubegroup.com
description: >- # this means to ignore newlines until "baseurl:"
  InCube Core is a set of C# libraries that provides extensions for functional
  programming, standard collection types, value parsing and formatting, and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://code.incubegroup.com" # the base hostname & protocol for your site, e.g. http://example.com

github_username: MartinMarciniszyn

markdown: kramdown
theme: minima

plugins:
  - jekyll-seo-tag

google_site_verification: "vdFHESfwS2Sq7sU_2UDfJRHwAEral6m21_8xmpLulU8"
